<?php

namespace Star\ChartBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * arretbusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class arretbusRepository extends DocumentRepository
{
    public function findAllEqual0()
    {
        return $this->createQueryBuilder()
        ->field('diff_TR')->equals('30')
        ->sort('p.date_requete', 'ASC')
        ->getQuery()
        ->execute();
    }
}