<?php

namespace Star\ChartBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ligneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneRepository extends DocumentRepository
{
}